[package]
name = "lspce-module"
version = "1.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lspce-macros = { path = "lspce-macros" }
lsp-types = "0.97.0"
crossbeam-channel = "0.5.4"
time = { version = "0.3", features = ["formatting", "macros", "local-offset"] }
emacs = "0.19.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "1.0"
anyhow = "1.0"
argh = "0.1"
wait-timeout = "0.2"

atomic_enum = "0.2"

[dev-dependencies]
lspce-module = { path = ".", features = ["test-utils"] }

[features]
test-utils = []

[profile.dev]
debug = 0

[profile.release]
lto = true
codegen-units = 1

[[test]]
name = "integrations"
path = "tests/integrations.rs"
required-features = ["test-utils"]
